### ISSUE TITLE
error in web_ui not getting my webpage i found a 404 error

### ISSUE THREAD

**Issue by venkynani** [posty/posty_webui#3]
I have installed a posty server using a ruby script and the process is completed successfully
but when am  open that ip in browser it shows an error 404 not found 
GET http://projectmgtprotrainingprogram.biz/posty_api/api/v1/domains
404 Not Found
337ms

**Comment by chicobico** [comment]
Is this fixed?
I get {"error":"Unauthorized. Invalid or expired token."}
