### ISSUE TITLE
Securing the WebUI

### ISSUE THREAD

**Issue by daande** [posty/posty_webui#7]
Is there a way to pass the URL and KEY that normally resides in settings.json in order to 'secure' this so that the URL/key would have to be known in order to access the webui?

**Comment by chicobico** [comment]
At the moment there is no chance to do that. We have not planned such a feature.

**Comment by daande** [comment]
@chicobico How would one secure the web UI so you require some sort of authentication?

**Comment by chicobico** [comment]
Protect your webui with .htaccess
